### ISSUE TITLE
Feature request: Custom tags

### ISSUE THREAD

**Issue by randohinn** [Chathula/Statica#1]
I think this would benefit immensely, by the opportunity to define custom tags, and behaviors for them.

**Comment by Chathula** [comment]
do u have any idea to do that? i like to know it more briefly.

**Comment by Chathula** [comment]
i'll update it. good idea.

**Comment by Chathula** [comment]
you can pass custom tags to view by putting custom tags into the object...

ex

``` javascript
var data = statico.use('filename.html', { "title" : "<titile>My title</title>", "text" : "<h1>this is the text</h1>" });
data.then(function (data)) {
  console.log(data);
}
```

like that...

thank you
